#!/bin/bash

set -e

PROD_DIR=/groups/sandwich/.pipeline
LOCAL_DIR=$(git rev-parse --show-toplevel)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

AXIOM_LINK="${LOCAL_DIR}/pipeline/lib/axiom"
# Create symlink if Axiom isn't present in local directory
if [[ ! -e "$AXIOM_LINK" ]]; then
    ln -s "${PROD_DIR}/pipeline/lib/axiom" "$AXIOM_LINK"
fi

# Update the env file
if [[ "${PROD_DIR}" != "${LOCAL_DIR}" ]]; then
    cp "${PROD_DIR}/pipeline/env.py" "${LOCAL_DIR}/pipeline/env.py"
    cp "${PROD_DIR}/pipeline/env_sg.py" "${LOCAL_DIR}/pipeline/env_sg.py"
fi

# Update the venv and set it up if it doesn't exist
source "${LOCAL_DIR}/.githooks/update-venv"
